services:
  postgres:
    container_name: diy
    image: postgres:15
    ports:
      - 5493:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diy
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: